## Imports

In [1]:
# Standard library imports,
import time
import random
import string
import datetime

# Third-party imports,
import numpy as np
import matplotlib.pyplot as plt
from dataset import COVID_DATASET
import shap
import pandas as pd

# PyTorch imports,
import torch
from torchsummary import summary
from torch.optim import SGD
from torch.utils.data import Dataset, DataLoader

##  Model Architecture & Training Method

In [15]:
class ConfigDataset(Dataset):
    def __init__(self, path):
        """X is the training input while Y is the target output."""

        # Loading PyTorch dataset,
        dataset = torch.load(path)
        self.X = dataset.X
        self.Y = dataset.Y
        self.features = dataset.features
        self.classes = dataset.classes
        del dataset

    def __len__(self):
        """Returns the number of objects in the dataset."""
        return self.X.shape[0]

    def __getitem__(self, index):
        "Returns a tuple of training input and target output."
        return self.X[index], self.Y[index]

class NeuralNetwork(torch.nn.Module):
    """The neutral network architecture."""

    def __init__(self):
        """Creating the layer stucture and activation functions of the neutral network."""
        super().__init__()

        # Layers,
        self.DenseLayer_INPUT = torch.nn.Linear(in_features = 48, out_features = 96)
        self.DenseLayer_HIDDEN_1 = torch.nn.Linear(in_features = 96, out_features = 96)
        self.DenseLayer_HIDDEN_2 = torch.nn.Linear(in_features = 96, out_features = 96)
        self.DenseLayer_HIDDEN_3 = torch.nn.Linear(in_features = 96, out_features = 24)
        self.DenseLayer_OUTPUT = torch.nn.Linear(in_features = 24, out_features = 2)

        # Activation functions,
        self.ReLU = torch.nn.ReLU()
        self.SoftMax = torch.nn.Softmax()

    def forward(self, X):
        """Defining the forward propagation."""

        X = self.DenseLayer_INPUT(X)
        X = self.ReLU(self.DenseLayer_HIDDEN_1(X))
        X = self.ReLU(self.DenseLayer_HIDDEN_2(X))
        X = self.ReLU(self.DenseLayer_HIDDEN_3(X))
        X = self.SoftMax(self.DenseLayer_OUTPUT(X))

        return X

def TrainModel(training_data, neural_network, model_name, n_epochs = 10, learning_rate = 0.01):

    print(model_name)
    summary(neural_network, (1, 48))
    print(" ")

    # Utilisation of CUDA if possible,
    if torch.cuda.is_available():
        device = torch.device("cuda")
        print(f'CUDA is available. Using GPU: {torch.cuda.get_device_name(0)}')
    else:
        device = torch.device("cpu")
        print('CUDA is not available. Using CPU.')

    neural_network.to(device)

    # Stochastic Gradient Descent (SGD) as optimiser,
    optimiser = SGD(neural_network.parameters(), lr = learning_rate)

    # Cross-Entropy loss function,
    loss_function = torch.nn.CrossEntropyLoss()

    losses = []
    epochs = np.arange(start = 1, stop = n_epochs, step = 1)

    for epoch in range(1, n_epochs + 1):
        epoch_loss = []
        stopwatch_start = time.time()
        for i, (X, Y) in enumerate(training_data):

            # Move data to selected device,
            X, Y = X.to(device), Y.to(device)

            # Back propagation,
            optimiser.zero_grad() 
            loss_value = loss_function(neural_network(X), Y) 
            epoch_loss.append(loss_value.item())
            loss_value.backward()
            optimiser.step()

        stopwatch_stop = time.time()
        epoch_time = round(stopwatch_stop - stopwatch_start, 2)
        epoch_avgloss = np.mean(epoch_loss)
        losses.append(epoch_avgloss)
        ETA = str(datetime.timedelta(seconds = (n_epochs - epoch)*epoch_time)).split(".")[0]
        update_string = f'[Completed Epoch: {epoch}/{n_epochs} - Time Taken: {epoch_time} secs - Loss: {epoch_avgloss:.5f} - ETA: {ETA} ]'
        print(update_string)

    torch.save(neural_network.state_dict(), f'{model_name}.pth')
    return np.array(epochs), np.array(losses)

def AssessModel(test_data, neural_network):

    X_test = test_data[:][0]
    Y_test = test_data[:][1]
    Yhat_test = neural_network(X_test)

    correct_counter = 0
    incorrect_counter = 0
    for Y, Yhat in zip(Y_test, Yhat_test):
        print(Y, Yhat)
        if Yhat.argmax() == Y.argmax():
            correct_counter += 1
        else:
            incorrect_counter += 1

    accuracy = correct_counter/(correct_counter + incorrect_counter)

    return accuracy

## Model Training Algorithm

In [3]:
# Hyperparameters,
EPOCHS = 25
BATCH_SIZE = 8
LEARNING_RATE = 0.01

if __name__ == "__main__":

    ID = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(5))
    model_name = "Model-" + ID

    # Creating and training neural network,
    training_dataset = ConfigDataset("training.pt")
    training_dataset_loaded = DataLoader(training_dataset, BATCH_SIZE)

    # Print example,
    train_features, train_labels = next(iter(training_dataset_loaded))
    print(f"Input Batch Shape: {train_features.size()}")
    print(f"Target Batch Shape: {train_labels.size()}")
    random_index = random.randint(0, BATCH_SIZE - 1)
    label = train_labels[random_index]
    print(f"Example Label: {label}")

    # Creating and training neural network,
    neural_network = NeuralNetwork()
    epoch_array, loss_array = TrainModel(training_dataset_loaded, neural_network, model_name, EPOCHS, LEARNING_RATE)

    # Testing neural network,
    test_dataset = ConfigDataset("test.pt")
    print("Accuracy: " + str(AssessModel(test_dataset, neural_network)))

Input Batch Shape: torch.Size([8, 48])
Target Batch Shape: torch.Size([8, 2])
Example Label: tensor([0., 1.])
Model-6PMIV
Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 1, 96]               4,704
├─Linear: 1-2                            [-1, 1, 96]               9,312
├─ReLU: 1-3                              [-1, 1, 96]               --
├─Linear: 1-4                            [-1, 1, 96]               9,312
├─ReLU: 1-5                              [-1, 1, 96]               --
├─Linear: 1-6                            [-1, 1, 24]               2,328
├─ReLU: 1-7                              [-1, 1, 24]               --
├─Linear: 1-8                            [-1, 1, 2]                50
├─Softmax: 1-9                           [-1, 1, 2]                --
Total params: 25,706
Trainable params: 25,706
Non-trainable params: 0
Total mult-adds (M): 0.03
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Param

Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


[Completed Epoch: 1/25 - Time Taken: 12.66 secs - Loss: 0.46164 - ETA: 0:05:03 ]
[Completed Epoch: 2/25 - Time Taken: 13.14 secs - Loss: 0.43000 - ETA: 0:05:02 ]
[Completed Epoch: 3/25 - Time Taken: 16.61 secs - Loss: 0.40742 - ETA: 0:06:05 ]
[Completed Epoch: 4/25 - Time Taken: 15.34 secs - Loss: 0.40586 - ETA: 0:05:22 ]
[Completed Epoch: 5/25 - Time Taken: 14.32 secs - Loss: 0.40484 - ETA: 0:04:46 ]
[Completed Epoch: 6/25 - Time Taken: 13.28 secs - Loss: 0.40414 - ETA: 0:04:12 ]
[Completed Epoch: 7/25 - Time Taken: 13.2 secs - Loss: 0.40372 - ETA: 0:03:57 ]
[Completed Epoch: 8/25 - Time Taken: 13.14 secs - Loss: 0.40324 - ETA: 0:03:43 ]
[Completed Epoch: 9/25 - Time Taken: 13.03 secs - Loss: 0.40279 - ETA: 0:03:28 ]
[Completed Epoch: 10/25 - Time Taken: 13.5 secs - Loss: 0.40243 - ETA: 0:03:22 ]
[Completed Epoch: 11/25 - Time Taken: 14.2 secs - Loss: 0.40231 - ETA: 0:03:18 ]
[Completed Epoch: 12/25 - Time Taken: 14.77 secs - Loss: 0.40212 - ETA: 0:03:12 ]
[Completed Epoch: 13/25 - Ti

## Model Loader

In [18]:
MODEL_FILE = "Model-6PMIV.pth"

# Loading model,
model = NeuralNetwork()
model.load_state_dict(torch.load(MODEL_FILE))
model.eval()

# Passing test data,
test_dataset = ConfigDataset("test.pt")
print("Accuracy: " + str(AssessModel(test_dataset, model)))

Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


tensor([1., 0.]) tensor([1.0000e+00, 1.0550e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.7419e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.4805e-04, 9.9975e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.7842e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.1410e-05, 9.9996e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.5245e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.2917e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.5571e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.1059e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.9961, 0.0039], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([8.2197e-05, 9.9992e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.4161e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.7915e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor(

tensor([1., 0.]) tensor([1.0000e+00, 4.1071e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.1342e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.7650, 0.2350], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.2014, 0.7986], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.5888e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.5456e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.9788e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.6938e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.9266e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.6534e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1643e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.1686e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 7.6902e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

tensor([1., 0.]) tensor([9.9999e-01, 1.0525e-05], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.9779, 0.0221], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.7722e-04, 9.9982e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.8402e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.9760e-04, 9.9980e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0000e+00, 2.7869e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([6.0937e-04, 9.9939e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.5312e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.3688e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.5618, 0.4382], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.4628e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.7517e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.7447e-04, 9.9973e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]

tensor([0., 1.]) tensor([0.0064, 0.9936], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.9791e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.9851e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.1342e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.3101e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.3331e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.3586e-04, 9.9936e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([5.7580e-04, 9.9942e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9994e-01, 5.6029e-05], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1645e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.2116e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9995e-01, 4.6892e-05], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.0616e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor(

tensor([1., 0.]) tensor([1.0000e+00, 1.1437e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.1219e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([6.9609e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.0595e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.1106e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.1443e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.3322e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0022, 0.9978], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.5797e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.3807e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.3116e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.7065e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0245, 0.9755], grad_fn=<UnbindBackward0>)
tensor([1., 0.]

tensor([0., 1.]) tensor([6.9487e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.0987e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.7408e-05, 9.9996e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.6225e-04, 9.9974e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0102, 0.9898], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.3967e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.1299e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.4943e-04, 9.9985e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.4678e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.9962, 0.0038], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.0955e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.8818e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.0284e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

tensor([1., 0.]) tensor([1.0000e+00, 3.0323e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.7149e-04, 9.9953e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.3637e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.7358e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.3634e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.2756e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9996e-01, 3.7991e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.0497e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.7662e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.2109e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.5238e-04, 9.9975e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.0215e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.0480e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)

tensor([1., 0.]) tensor([0.9691, 0.0309], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.6176e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 8.1207e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.2161e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.8038e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0081, 0.9919], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([4.1652e-05, 9.9996e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.2521e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0134, 0.9866], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0034, 0.9966], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1751e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.5255e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.2229, 0.7771], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.

tensor([1., 0.]) tensor([1.0000e+00, 3.3948e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.5535e-05, 9.9996e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0628, 0.9372], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.9791e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.2922e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.4959e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.1638e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.0191e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.4835e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([3.1085e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.1683e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.1906e-04, 9.9978e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.9124e-08], grad_fn=<UnbindBackward0>)
tensor(

tensor([0., 1.]) tensor([0.1255, 0.8745], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0611, 0.9389], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([3.3175e-04, 9.9967e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.0464e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1932e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.5476e-05, 9.9993e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.7710e-05, 9.9990e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9998e-01, 1.9046e-05], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.6978e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.0972e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.4672e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.6940e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.2204e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

tensor([1., 0.]) tensor([9.9973e-01, 2.7301e-04], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0012, 0.9988], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.0693e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0016, 0.9984], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0184, 0.9816], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.6707e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.6676e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.1233e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.8653, 0.1347], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0083, 0.9917], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.6503e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.7517e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 5.7895e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.7489, 0.2511

tensor([1., 0.]) tensor([1.0000e+00, 8.2970e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.7257e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.4088e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.5177e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.2714e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.6391e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.4091e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([4.4712e-05, 9.9996e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.8803e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.2204e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.3647e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.1342e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0191, 0.9809], grad_fn=<UnbindBackward0>)
tensor(

tensor([0., 1.]) tensor([8.8518e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0023, 0.9977], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.0233e-04, 9.9960e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.7701e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.4001e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.1828e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.0309e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0793e-04, 9.9989e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.8105e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.3793e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0222, 0.9778], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.2338e-04, 9.9968e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.9200e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

tensor([1., 0.]) tensor([1.0000e+00, 4.6955e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.1781e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0038, 0.9962], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.1239e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.9184e-04, 9.9971e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.7894e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.4358e-10, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.0014e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.8071e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.3818e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.1518e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.4770e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.5763e-07], grad_fn=<UnbindBackward0>)
tensor(

tensor([0., 1.]) tensor([9.0924e-05, 9.9991e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.5975e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.4517e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.3322e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.4639e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.0716e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.0895e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.2282e-04, 9.9978e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.7753e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0022, 0.9978], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([8.9851e-05, 9.9991e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.0616e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.5755e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor(

tensor([1., 0.]) tensor([1.0000e+00, 8.8477e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0808, 0.9192], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.1975e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 7.4675e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.9815e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.5792e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0667e-04, 9.9989e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.9266e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.9543e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.2171e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0048, 0.9952], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.0145e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.8670e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

tensor([1., 0.]) tensor([1.0000e+00, 2.0464e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.4625e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0241, 0.9759], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.6614e-04, 9.9983e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.2281e-04, 9.9988e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.2618e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.3793e-04, 9.9976e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9998e-01, 1.8042e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.8633e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.1009e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9974e-01, 2.5950e-04], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.3405e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.5015e-08], grad_fn=<UnbindBackward0>)
tensor(

tensor([0., 1.]) tensor([8.5820e-05, 9.9991e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0023, 0.9977], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9990e-01, 9.8284e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.9287e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9993e-01, 7.0174e-05], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.6515e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.9578e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.3802e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.5390e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.6233e-04, 9.9984e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.9915, 0.0085], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.4230e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.1377e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]

tensor([1., 0.]) tensor([1.0000e+00, 1.6670e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.3161e-04, 9.9937e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.7635e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.7266e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.4662, 0.5338], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.0323e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.6083e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0034, 0.9966], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9994e-01, 6.2015e-05], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.5987e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9987e-01, 1.3133e-04], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.5226e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.9266e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]

tensor([1., 0.]) tensor([1.0000e+00, 2.5560e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.9694e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.3273e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0644e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.9606e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.0036e-04, 9.9960e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.0971e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.7203e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.3116e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.4413e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.6005e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.9248e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.5201e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)

tensor([0., 1.]) tensor([1.5538e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.2161e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.9694e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.3626e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 5.9684e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.1342e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.8703e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.6206e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.6586e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.9341e-04, 9.9981e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.5518e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 1.4793e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.0345e-07], grad_fn=<UnbindBackward0>)

tensor([1., 0.]) tensor([1.0000e+00, 1.9266e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.2693e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1125e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1259e-04, 9.9989e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.0701e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.6498e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.3305e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.0809e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.7548e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.6583e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9990e-01, 1.0089e-04], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.0832e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.0101e-07], grad_fn=<UnbindBackward0>)

tensor([0., 1.]) tensor([8.9615e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0042, 0.9958], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.9906, 0.0094], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9950e-01, 4.9766e-04], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 1.0384e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.1953e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9996e-01, 4.4808e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9996e-01, 3.6759e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9996e-01, 4.1050e-05], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.8248e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.8870e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0526, 0.9474], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.6460e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor

tensor([1., 0.]) tensor([1.0000e+00, 1.2874e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.3716e-05, 9.9991e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0122, 0.9878], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.2239e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9998e-01, 1.5472e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.5233, 0.4767], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.5942e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.9857, 0.0143], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.2224e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.9825e-05, 9.9994e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0594e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0486e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1362e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor

tensor([1., 0.]) tensor([1.0000e+00, 5.4725e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.3392e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.2742e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.0699e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.7923e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.2013e-05, 9.9996e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([6.7232e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.3443e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.4945e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.8013e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.3735e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.5679e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.0326e-04, 9.9960e-01], grad_fn=<UnbindBackward0>)

tensor([0., 1.]) tensor([1.1037e-04, 9.9989e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.9287e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.7610e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.2021e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0050, 0.9950], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9996e-01, 4.1050e-05], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.0947e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.6940e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.4923e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.5138e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.0430e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.8296e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0192e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor(

tensor([0., 1.]) tensor([2.1325e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.5950e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.5405, 0.4595], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.8788e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.6645e-10, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 1.3741e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0140, 0.9860], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.4386e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.6573e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0366, 0.9634], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.1016e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.9609e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.1135e-05, 9.9995e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor

tensor([0., 1.]) tensor([2.9440e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.4914e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.2708e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.3427e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.9811, 0.0189], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.7773e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.1870e-04, 9.9938e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.8023e-05, 9.9996e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.8477e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.6269e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0725, 0.9275], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.2707e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.7869e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

tensor([0., 1.]) tensor([4.5305e-05, 9.9995e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.6206e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.1566e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.4011e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.0285e-04, 9.9950e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.2965e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.5227, 0.4773], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.9731e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.8570e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.1877e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.9922e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0022, 0.9978], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.9033e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

tensor([1., 0.]) tensor([1.0000e+00, 1.9991e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.0965e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.1447e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.7298e-05, 9.9993e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.8376e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.4803e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.9170e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.9195e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 6.0705e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.9850, 0.0150], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.3103e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.0309e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.3305e-08], grad_fn=<UnbindBackward0>)
tensor(

tensor([0., 1.]) tensor([0.0347, 0.9653], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.9949e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.4950e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.7349e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([4.9010e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.1494e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.3882e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.3371e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.9466e-04, 9.9961e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.2993e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0037, 0.9963], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.1983e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.1679e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]

tensor([0., 1.]) tensor([1.9657e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.4627e-04, 9.9985e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0037, 0.9963], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0103, 0.9897], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.6682e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9984e-01, 1.6309e-04], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.5255e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.9447e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.8182e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0128, 0.9872], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0540, 0.9460], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.0580e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1332e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000

tensor([0., 1.]) tensor([1.1518e-04, 9.9988e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.4743e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0000e+00, 1.0432e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.3838e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0028, 0.9972], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.6741e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.5518e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.9975, 0.0025], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.0455e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9996e-01, 3.9553e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0069, 0.9931], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.5569e-04, 9.9984e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 5.2289e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor

tensor([0., 1.]) tensor([2.4440e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0905e-04, 9.9989e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0011, 0.9989], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.7166, 0.2834], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.0016e-04, 9.9950e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.7232e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.6010e-04, 9.9984e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.5575e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.7790e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.6650e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0093, 0.9907], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.2210e-05, 9.9992e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.9977, 0.0023], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000

tensor([0., 1.]) tensor([2.6711e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.7015e-04, 9.9963e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 7.0768e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.3647e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.2225e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.9709e-05, 9.9994e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.7869e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.8673e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.9961e-01, 3.8856e-04], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.0372e-05, 9.9996e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.2965e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0016e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.0557e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)

tensor([0., 1.]) tensor([1.4981e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.9959, 0.0041], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.8011e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0440, 0.9560], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([4.6304e-05, 9.9995e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.0343e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0566e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0013, 0.9987], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.2690e-10, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.7479e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.1956e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.8758e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0013, 0.9987], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.3699

tensor([1., 0.]) tensor([1.0000e+00, 1.4583e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.8042e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.6479e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.7713e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.0607e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 9.5518e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.8935, 0.1065], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9995e-01, 4.9899e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.3600e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.7318e-04, 9.9973e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0057, 0.9943], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.9615e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0659e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]

tensor([1., 0.]) tensor([0.0011, 0.9989], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.3882e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.6624e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999e-01, 5.7947e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([5.9851e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.8369e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.7725e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.0840e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0027, 0.9973], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0045, 0.9955], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.2939e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.6310, 0.3690], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.1810e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9999

tensor([1., 0.]) tensor([1.0000e+00, 6.7632e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([2.7901e-04, 9.9972e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.1035e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0699, 0.9301], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.8736e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.5568e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.2161e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0031, 0.9969], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.9388e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.9809e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.0056e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.8198e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([2.8214e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]

tensor([1., 0.]) tensor([7.9182e-04, 9.9921e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.3782e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.7914e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.7435e-04, 9.9963e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.5015e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.2661, 0.7339], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0000e+00, 3.5512e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0075, 0.9925], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.6789e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.9976e-01, 2.4303e-04], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.1881e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0494e-05, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0026, 0.9974], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor

tensor([1., 0.]) tensor([1.0000e+00, 3.8801e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0335, 0.9665], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.3716e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 8.6676e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0164e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.6955e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 6.0941e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.2338e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.8539e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.2143e-08, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.8266e-04, 9.9912e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.5480e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.9051e-08], grad_fn=<UnbindBackward0>)
tensor(

tensor([0., 1.]) tensor([0.0353, 0.9647], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.8116e-05, 9.9995e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.2164, 0.7836], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.5255e-06], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.2911e-04, 9.9987e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0150, 0.9850], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.1903e-07], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.4678e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.9740e-04, 9.9970e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.2965e-08], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.1907e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.8929e-05, 9.9997e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([4.0872e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor

tensor([0., 1.]) tensor([1.5590e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.7093e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 7.5368e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.1961e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0061, 0.9939], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0926, 0.9074], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.9792, 0.0208], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.6123e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.3600e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([3.6997e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.3495e-04, 9.9977e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([9.9421e-06, 9.9999e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0035, 0.9965], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000

tensor([0., 1.]) tensor([1.2513e-04, 9.9987e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.3275, 0.6725], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 3.3164e-09], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([0.0387, 0.9613], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0410e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.3881e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.0575e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.1218e-05, 9.9998e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.1001e-04, 9.9989e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 5.7914e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.4502e-09, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 4.6146e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([6.2995e-05, 9.9994e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

tensor([1., 0.]) tensor([1.0000e+00, 8.1982e-07], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([8.6888e-04, 9.9913e-01], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([5.0469e-04, 9.9950e-01], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([2.8225e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([7.3941e-07, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.0246e-06], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.4937e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([1.0511e-06, 1.0000e+00], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([9.9994e-01, 5.6029e-05], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 2.3423e-08], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.4761, 0.5239], grad_fn=<UnbindBackward0>)
tensor([0., 1.]) tensor([0.0035, 0.9965], grad_fn=<UnbindBackward0>)
tensor([1., 0.]) tensor([1.0000e+00, 1.3646e-09], grad_fn=<UnbindBackward0>)
tensor([0., 1.]

In [16]:
# Loading input dataframe,
df_input = pd.DataFrame(data = pd.read_csv("model-input.csv"))

# Correcting datatypes,
df_input = df_input.astype("string")
df_input["AGE"] = df_input["AGE"].astype(np.float32)
df_input

USMR MEDICAL_UNIT     SEX PATIENT_TYPE PNEUMONIA   AGE PREGNANT DIABETES  \
0    No            3    Male     Hospital        No  21.0       No       No   
1    No            3    Male     Hospital        No  19.0       No       No   
2    No            3    Male     Hospital        No  48.0       No       No   
3    No            3  Female     Hospital        No  47.0       No       No   
4    No            1    Male     Hospital        No  24.0       No       No   
5    No            1    Male     Hospital        No  30.0       No       No   
6    No            1    Male         Home        No  55.0       No       No   
7    No            1  Female         Home        No  48.0       No      Yes   
8    No            1  Female         Home        No  23.0       No       No   
9    No            1  Female     Hospital       Yes  80.0       No       No   
10   No            1    Male         Home        No  61.0       No       No   
11   No            1    Male         Home        No  54.0       No       No   
12   No            1  Female         Home        No  64.0       No       No   
13   No            1    Male     Hospital       Yes  59.0       No      Yes   
14   No            1    Male         Home        No  30.0       No       No   
15   No            1    Male         Home        No  45.0       No       No   
16   No            1  Female         Home        No  26.0       No       No   
17   No            1  Female         Home        No  38.0       No       No   
18   No            1    Male         Home        No  24.0       No       No   
19   No            1    Male         Home        No  32.0       No       No   
20   No            1    Male         Home        No  49.0       No       No   
21   No            1    Male         Home        No  39.0       No       No   
22   No            1    Male         Home        No  27.0       No       No   
23   No            1    Male     Hospital       Yes  45.0       No       No   
24   No            4  Female         Home       Yes  69.0       No       No   
25  Yes            4    Male     Hospital       Yes  59.0       No       No   
26  Yes            4    Male     Hospital       Yes  68.0       No       No   
27   No            4    Male     Hospital       Yes  64.0       No       No   
28   No            4    Male     Hospital       Yes  83.0       No       No   
29  Yes            4  Female     Hospital       Yes  80.0       No      Yes   
30  Yes            4    Male     Hospital       Yes  47.0       No       No   
31  Yes            4  Female     Hospital       Yes  73.0       No       No   
32  Yes            4  Female     Hospital       Yes  92.0       No       No   
33  Yes            4    Male         Home       Yes  49.0       No       No   
34  Yes            4  Female     Hospital       Yes  58.0       No       No   
35   No            4    Male     Hospital       Yes  75.0       No       No   
36  Yes            4    Male     Hospital       Yes  80.0       No      Yes   
37  Yes            4  Female     Hospital       Yes  89.0       No       No   
38   No            4    Male     Hospital       Yes  42.0       No       No   
39   No            4  Female     Hospital       Yes  70.0       No      Yes   
40   No            4  Female     Hospital       Yes  47.0       No       No   
41  Yes            4    Male         Home       Yes  53.0       No       No   
42  Yes            4    Male     Hospital       Yes  44.0       No       No   
43  Yes            4  Female         Home       Yes  65.0       No      Yes   
44  Yes            4    Male     Hospital       Yes  74.0       No       No   
45   No            4    Male     Hospital       Yes  74.0       No       No   
46   No            4  Female     Hospital       Yes  50.0       No      Yes   

   COPD ASTHMA INMSUPR HYPERTENSION OTHER_DISEASE CARDIOVASCULAR OBESITY  \
0    No     No      No           No            No             No      No   
1    No     No      No           No            No         

In [17]:
columns_encoded = []
for dict_key in test_dataset.features:

    if len(test_dataset.features[dict_key]) != 0:
        for unique_value in test_dataset.features[dict_key]:
            columns_encoded.append(dict_key + "_" + unique_value)
    else:
        columns_encoded.append(dict_key)

df_encoded = pd.DataFrame(columns = columns_encoded)

rows_params = []
for index, row in df_input.iterrows():
    row_param = []
    for dict_key in test_dataset.features:
        if type(row[dict_key]) is str:
            row_param.append(dict_key + "_" + row[dict_key])
        else:
            row_param.append((dict_key, row[dict_key]))
    rows_params.append(row_param)

encoded_rows = []
for row_param in rows_params:
    encoded_row = {}
    for param in row_param:
        if type(param) is str:
            for column in df_encoded:
                if param == column:
                    encoded_row[column] = 1
        else:
            for column in df_encoded:
                if param[0] == column:
                    encoded_row[column] = param[1]
    encoded_rows.append(encoded_row)

for encoded_row in encoded_rows:
    df_encoded.loc[len(df_encoded)] = encoded_row
df_encoded = df_encoded.fillna(0)
df_encoded = df_encoded.astype("float32")
df_encoded

USMR_No  USMR_Yes  MEDICAL_UNIT_1  MEDICAL_UNIT_2  MEDICAL_UNIT_3  \
0       1.0       0.0             0.0             0.0             1.0   
1       1.0       0.0             0.0             0.0             1.0   
2       1.0       0.0             0.0             0.0             1.0   
3       1.0       0.0             0.0             0.0             1.0   
4       1.0       0.0             1.0             0.0             0.0   
5       1.0       0.0             1.0             0.0             0.0   
6       1.0       0.0             1.0             0.0             0.0   
7       1.0       0.0             1.0             0.0             0.0   
8       1.0       0.0             1.0             0.0             0.0   
9       1.0       0.0             1.0             0.0             0.0   
10      1.0       0.0             1.0             0.0             0.0   
11      1.0       0.0             1.0             0.0             0.0   
12      1.0       0.0             1.0             0.0             0.0   
13      1.0       0.0             1.0             0.0             0.0   
14      1.0       0.0             1.0             0.0             0.0   
15      1.0       0.0             1.0             0.0             0.0   
16      1.0       0.0             1.0             0.0             0.0   
17      1.0       0.0             1.0             0.0             0.0   
18      1.0       0.0             1.0             0.0             0.0   
19      1.0       0.0             1.0             0.0             0.0   
20      1.0       0.0             1.0             0.0             0.0   
21      1.0       0.0             1.0             0.0             0.0   
22      1.0       0.0             1.0             0.0             0.0   
23      1.0       0.0             1.0             0.0             0.0   
24      1.0       0.0             0.0             0.0             0.0   
25      0.0       1.0             0.0             0.0             0.0   
26      0.0       1.0             0.0             0.0             0.0   
27      1.0       0.0             0.0             0.0             0.0   
28      1.0       0.0             0.0             0.0             0.0   
29      0.0       1.0             0.0             0.0             0.0   
30      0.0       1.0             0.0             0.0             0.0   
31      0.0       1.0             0.0             0.0             0.0   
32      0.0       1.0             0.0             0.0             0.0   
33      0.0       1.0             0.0             0.0             0.0   
34      0.0       1.0             0.0             0.0             0.0   
35      1.0       0.0             0.0             0.0             0.0   
36      0.0       1.0             0.0             0.0             0.0   
37      0.0       1.0             0.0             0.0             0.0   
38      1.0       0.0             0.0             0.0             0.0   
39      1.0       0.0             0.0             0.0             0.0   
40      1.0       0.0             0.0             0.0             0.0   
41      0.0       1.0             0.0             0.0             0.0   
42      0.0       1.0             0.0             0.0             0.0   
43      0.0       1.0             0.0             0.0             0.0   
44      0.0       1.0             0.0             0.0             0.0   
45      1.0       0.0             0.0             0.0             0.0   
46      1.0       0.0             0.0             0.0             0.0   

    MEDICAL_UNIT_4  MEDICAL_UNIT_5  MEDICAL_UNIT_6  MEDICAL_UNIT_7  \
0              0.0             0.0             0.0             0.0   
1              0.0             0.0             0.0             0.0   
2              0.0             0.0             0.0             0.0   
3              0.0             0.0             0.0             0.0   
4              0.0             0.0             0.0             0.0   
5              0.0             0.0             0.0             0.0   
6        

In [13]:
X = df_encoded.to_numpy()
X = torch.tensor(X, dtype = torch.float32)
Y = model(X).detach().numpy()

"""df_Y = pd.DataFrame(columns = ["DESCEASED_No", "DESCEASED_Yes"])
for probabilities in Y:
    df_Y.loc[len(df_Y)] = probabilities"""

Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


In [21]:
Y

array([[7.1885004e-19, 1.0000000e+00],
       [6.4799470e-17, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [9.5165138e-23, 1.0000000e+00],
       [6.2954584e-30, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [1.7147255e-23, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [5.9582317e-32, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [4.3274513e-27, 1.0000000e+00],
       [3.6335669e-42, 1.0000000e+00],
       [9.2470344e-25, 1.0000000e+00],
       [2.3794577e-34, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [8.8842323e-43, 1.0000000e+00],
       [2.3609118e-28, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.